### ISSUE TITLE
多行不滚的设置

### ISSUE THREAD

**Issue by EdenChow** [huangxuan518/HXTagsView#16]
如何设置 多行不滚啊? 你的demo好复杂。

**Comment by huangxuan518** [comment]
@EdenChow  设置高度大于等于计算的高度就不会滚动，有个方法可以获取高度的

**Comment by yang152412** [comment]
在计算tag 标签大小的时候，`frame.size.width + _tagAttribute.tagSpace;`，为何要添加上这个间距，如果 `frame.size.width` 正好 == `maxSize.width`，则会给出警告 
`
The behavior of the UICollectionViewFlowLayout is not defined because:
the item width must be less than the width of the UICollectionView minus the section insets left and right values, minus the content insets left and right values.
Please check the values returned by the delegate.
`
